//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIEDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        public string codigoProyecto { get; set; }
        public string objetivoEspecifico { get; set; }
        public int idCodigo { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
