//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.ProyectoXDepartamento = new HashSet<ProyectoXDepartamento>();
        }
    
        public int Id { get; set; }
        public string NombreProyecto { get; set; }
    
        public virtual ICollection<ProyectoXDepartamento> ProyectoXDepartamento { get; set; }
    }
}
