//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoDeTrabajoXTipoHora
    {
        public int Id { get; set; }
        public int IdEquipoDeTrabajo { get; set; }
        public int IdTipoHora { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinalizacion { get; set; }
        public Nullable<int> CantidadHoras { get; set; }
    
        public virtual EquipoDeTrabajo EquipoDeTrabajo { get; set; }
        public virtual TipoHora TipoHora { get; set; }
    }
}
