//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuenteFinanciamiento
    {
        public FuenteFinanciamiento()
        {
            this.PresupuestoProyecto = new HashSet<PresupuestoProyecto>();
        }
    
        public int Id { get; set; }
        public string FuenteFinanciamiento1 { get; set; }
    
        public virtual ICollection<PresupuestoProyecto> PresupuestoProyecto { get; set; }
    }
}
