//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idioma
    {
        public Idioma()
        {
            this.InvestigadorXIdioma = new HashSet<InvestigadorXIdioma>();
        }
    
        public int Id { get; set; }
        public string NombreIdioma { get; set; }
    
        public virtual ICollection<InvestigadorXIdioma> InvestigadorXIdioma { get; set; }
    }
}
