//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe
    {
        public int Id { get; set; }
        public string TituloInforme { get; set; }
        public int IdTipoInforme { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public Nullable<System.DateTime> FechaDeEntrega { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string MemorandoDIP { get; set; }
        public string Observaciones { get; set; }
        public string CodigoProyecto { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual TipoInforme TipoInforme { get; set; }
    }
}
