//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestigadorXSubdisciplina
    {
        public int Id { get; set; }
        public int IdSubdisciplina { get; set; }
        public string NumIdentidad { get; set; }
        public int IdDisciplina { get; set; }
    
        public virtual DisciplinaCientifica DisciplinaCientifica { get; set; }
        public virtual Investigador Investigador { get; set; }
        public virtual Subdisciplina Subdisciplina { get; set; }
    }
}
