//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestigadorXIdioma
    {
        public int Id { get; set; }
        public string NumIdentidad { get; set; }
        public int IdIdioma { get; set; }
        public int NivelLectura { get; set; }
        public int NivelHabla { get; set; }
        public int NivelEscritura { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual Investigador Investigador { get; set; }
        public virtual NivelIdioma NivelIdioma { get; set; }
        public virtual NivelIdioma NivelIdioma1 { get; set; }
        public virtual NivelIdioma NivelIdioma2 { get; set; }
    }
}
