//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigador
    {
        public Investigador()
        {
            this.EntradaBitacora = new HashSet<EntradaBitacora>();
            this.EquipoDeTrabajo = new HashSet<EquipoDeTrabajo>();
            this.InvestigadorXEscuela = new HashSet<InvestigadorXEscuela>();
            this.InvestigadorXIdioma = new HashSet<InvestigadorXIdioma>();
            this.InvestigadorXSubdisciplina = new HashSet<InvestigadorXSubdisciplina>();
            this.ProductoObjetivo = new HashSet<ProductoObjetivo>();
            this.Proyecto = new HashSet<Proyecto>();
            this.Proyecto1 = new HashSet<Proyecto>();
        }
    
        public string NumIdentidad { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string CorreoElectronico { get; set; }
        public string TelefonoMovil { get; set; }
        public bool EstadoActual { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int TipoIdentificacion { get; set; }
        public int PaisNacimiento { get; set; }
        public string Sexo { get; set; }
    
        public virtual ICollection<EntradaBitacora> EntradaBitacora { get; set; }
        public virtual ICollection<EquipoDeTrabajo> EquipoDeTrabajo { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual TipoDeIdentificacion TipoDeIdentificacion { get; set; }
        public virtual ICollection<InvestigadorXEscuela> InvestigadorXEscuela { get; set; }
        public virtual ICollection<InvestigadorXIdioma> InvestigadorXIdioma { get; set; }
        public virtual ICollection<InvestigadorXSubdisciplina> InvestigadorXSubdisciplina { get; set; }
        public virtual ICollection<ProductoObjetivo> ProductoObjetivo { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual ICollection<Proyecto> Proyecto1 { get; set; }
    }
}
