//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public bool EstaCumplida { get; set; }
        public int IdObjectivoEspecifico { get; set; }
    
        public virtual ObjetivoEspecifico ObjetivoEspecifico { get; set; }
    }
}
