//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class VieEntidades : DbContext
    {
        public VieEntidades()
            : base("name=VieEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AmpliacionFechas> AmpliacionFechas { get; set; }
        public DbSet<AreaFrascati> AreaFrascati { get; set; }
        public DbSet<Canton> Canton { get; set; }
        public DbSet<Colaborador> Colaborador { get; set; }
        public DbSet<Compra> Compra { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<DisciplinaCientifica> DisciplinaCientifica { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<EntradaBitacora> EntradaBitacora { get; set; }
        public DbSet<EquipoDeTrabajo> EquipoDeTrabajo { get; set; }
        public DbSet<EquipoDeTrabajoXTipoHora> EquipoDeTrabajoXTipoHora { get; set; }
        public DbSet<Escuela> Escuela { get; set; }
        public DbSet<EstadoDeProyecto> EstadoDeProyecto { get; set; }
        public DbSet<FuenteFinanciamiento> FuenteFinanciamiento { get; set; }
        public DbSet<Idioma> Idioma { get; set; }
        public DbSet<Incidencia> Incidencia { get; set; }
        public DbSet<Informe> Informe { get; set; }
        public DbSet<Investigador> Investigador { get; set; }
        public DbSet<InvestigadorXEscuela> InvestigadorXEscuela { get; set; }
        public DbSet<InvestigadorXIdioma> InvestigadorXIdioma { get; set; }
        public DbSet<InvestigadorXSubdisciplina> InvestigadorXSubdisciplina { get; set; }
        public DbSet<Meta> Meta { get; set; }
        public DbSet<ModalidadProyecto> ModalidadProyecto { get; set; }
        public DbSet<NivelDeResponsabilidad> NivelDeResponsabilidad { get; set; }
        public DbSet<NivelIdioma> NivelIdioma { get; set; }
        public DbSet<ObjetivoEspecifico> ObjetivoEspecifico { get; set; }
        public DbSet<ODS> ODS { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<PalabraClave> PalabraClave { get; set; }
        public DbSet<Partida> Partida { get; set; }
        public DbSet<PlanDeAccion> PlanDeAccion { get; set; }
        public DbSet<PlanteamientoProyecto> PlanteamientoProyecto { get; set; }
        public DbSet<PoblacionBeneficiaria> PoblacionBeneficiaria { get; set; }
        public DbSet<PresupuestoProyecto> PresupuestoProyecto { get; set; }
        public DbSet<ProductoObjetivo> ProductoObjetivo { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Proyecto> Proyecto { get; set; }
        public DbSet<ProyectoXBeneficiaria> ProyectoXBeneficiaria { get; set; }
        public DbSet<ProyectoXDepartamento> ProyectoXDepartamento { get; set; }
        public DbSet<ProyectoXFrascati> ProyectoXFrascati { get; set; }
        public DbSet<ProyectoXODS> ProyectoXODS { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Riesgo> Riesgo { get; set; }
        public DbSet<Sede> Sede { get; set; }
        public DbSet<SetDatosGenerales> SetDatosGenerales { get; set; }
        public DbSet<SubAreaFrascati> SubAreaFrascati { get; set; }
        public DbSet<Subdisciplina> Subdisciplina { get; set; }
        public DbSet<SubODS> SubODS { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoDeIdentificacion> TipoDeIdentificacion { get; set; }
        public DbSet<TipoDepartamento> TipoDepartamento { get; set; }
        public DbSet<TipoDeProceso> TipoDeProceso { get; set; }
        public DbSet<TipoHora> TipoHora { get; set; }
        public DbSet<TipoInforme> TipoInforme { get; set; }
        public DbSet<TipoParticipacion> TipoParticipacion { get; set; }
        public DbSet<TipoProyecto> TipoProyecto { get; set; }
        public DbSet<UbicacionGeografica> UbicacionGeografica { get; set; }
    
        public virtual ObjectResult<Pr_Colaborador_Seleccionar_Result> Pr_Colaborador_Seleccionar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Colaborador_Seleccionar_Result>("Pr_Colaborador_Seleccionar");
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Compra_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Compra_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_Compra_Insertar_Result> Pr_Compra_Insertar(string nombreProducto, Nullable<int> cantidad, Nullable<int> precioTotal, string codigoProyecto)
        {
            var nombreProductoParameter = nombreProducto != null ?
                new ObjectParameter("NombreProducto", nombreProducto) :
                new ObjectParameter("NombreProducto", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var precioTotalParameter = precioTotal.HasValue ?
                new ObjectParameter("PrecioTotal", precioTotal) :
                new ObjectParameter("PrecioTotal", typeof(int));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Compra_Insertar_Result>("Pr_Compra_Insertar", nombreProductoParameter, cantidadParameter, precioTotalParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_Compra_SeleccionarXProyecto_Result> Pr_Compra_SeleccionarXProyecto(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Compra_SeleccionarXProyecto_Result>("Pr_Compra_SeleccionarXProyecto", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_EntradaBitacora_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_EntradaBitacora_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_EntradaBitacora_Insertar_Result> Pr_EntradaBitacora_Insertar(string descripcion, string responsable, string cedulaResponsable, Nullable<System.DateTime> fechaYHora, string codigoProyecto)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("Responsable", responsable) :
                new ObjectParameter("Responsable", typeof(string));
    
            var cedulaResponsableParameter = cedulaResponsable != null ?
                new ObjectParameter("CedulaResponsable", cedulaResponsable) :
                new ObjectParameter("CedulaResponsable", typeof(string));
    
            var fechaYHoraParameter = fechaYHora.HasValue ?
                new ObjectParameter("FechaYHora", fechaYHora) :
                new ObjectParameter("FechaYHora", typeof(System.DateTime));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_EntradaBitacora_Insertar_Result>("Pr_EntradaBitacora_Insertar", descripcionParameter, responsableParameter, cedulaResponsableParameter, fechaYHoraParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_EntradaBitacora_Seleccionar_Result> Pr_EntradaBitacora_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_EntradaBitacora_Seleccionar_Result>("Pr_EntradaBitacora_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_EquipoDeTrabajo_Seleccionar_Result> Pr_EquipoDeTrabajo_Seleccionar(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_EquipoDeTrabajo_Seleccionar_Result>("Pr_EquipoDeTrabajo_Seleccionar", codigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Incidencia_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Incidencia_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_Incidencia_Insertar_Result> Pr_Incidencia_Insertar(string tituloIncidencia, string descripcion, string codigoProyecto)
        {
            var tituloIncidenciaParameter = tituloIncidencia != null ?
                new ObjectParameter("TituloIncidencia", tituloIncidencia) :
                new ObjectParameter("TituloIncidencia", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Incidencia_Insertar_Result>("Pr_Incidencia_Insertar", tituloIncidenciaParameter, descripcionParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_Incidencias_Seleccionar_Result> Pr_Incidencias_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Incidencias_Seleccionar_Result>("Pr_Incidencias_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Informe_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Informe_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_Informe_Insertar_Result> Pr_Informe_Insertar(string tituloInforme, Nullable<int> idTipoInforme, Nullable<System.DateTime> fechaProgramada, string estado, string memorandoDIP, string observaciones, string codigoProyecto)
        {
            var tituloInformeParameter = tituloInforme != null ?
                new ObjectParameter("TituloInforme", tituloInforme) :
                new ObjectParameter("TituloInforme", typeof(string));
    
            var idTipoInformeParameter = idTipoInforme.HasValue ?
                new ObjectParameter("IdTipoInforme", idTipoInforme) :
                new ObjectParameter("IdTipoInforme", typeof(int));
    
            var fechaProgramadaParameter = fechaProgramada.HasValue ?
                new ObjectParameter("FechaProgramada", fechaProgramada) :
                new ObjectParameter("FechaProgramada", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var memorandoDIPParameter = memorandoDIP != null ?
                new ObjectParameter("MemorandoDIP", memorandoDIP) :
                new ObjectParameter("MemorandoDIP", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Informe_Insertar_Result>("Pr_Informe_Insertar", tituloInformeParameter, idTipoInformeParameter, fechaProgramadaParameter, estadoParameter, memorandoDIPParameter, observacionesParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_Informe_SeleccionarXProyecto_Result> Pr_Informe_SeleccionarXProyecto(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Informe_SeleccionarXProyecto_Result>("Pr_Informe_SeleccionarXProyecto", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<string> Pr_Investigador_AgregarAProy(string numIdentidad, Nullable<int> idSetDatos, Nullable<int> idCondicionDeParticipacion, Nullable<int> idEscuela, string areaConocimiento)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            var idSetDatosParameter = idSetDatos.HasValue ?
                new ObjectParameter("IdSetDatos", idSetDatos) :
                new ObjectParameter("IdSetDatos", typeof(int));
    
            var idCondicionDeParticipacionParameter = idCondicionDeParticipacion.HasValue ?
                new ObjectParameter("IdCondicionDeParticipacion", idCondicionDeParticipacion) :
                new ObjectParameter("IdCondicionDeParticipacion", typeof(int));
    
            var idEscuelaParameter = idEscuela.HasValue ?
                new ObjectParameter("IdEscuela", idEscuela) :
                new ObjectParameter("IdEscuela", typeof(int));
    
            var areaConocimientoParameter = areaConocimiento != null ?
                new ObjectParameter("AreaConocimiento", areaConocimiento) :
                new ObjectParameter("AreaConocimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Pr_Investigador_AgregarAProy", numIdentidadParameter, idSetDatosParameter, idCondicionDeParticipacionParameter, idEscuelaParameter, areaConocimientoParameter);
        }
    
        public virtual ObjectResult<string> Pr_Investigador_AgregarHoras(Nullable<int> idEquipoDeTrabajo, Nullable<int> idTipoHora, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinalizacion, Nullable<int> cantidadHoras)
        {
            var idEquipoDeTrabajoParameter = idEquipoDeTrabajo.HasValue ?
                new ObjectParameter("IdEquipoDeTrabajo", idEquipoDeTrabajo) :
                new ObjectParameter("IdEquipoDeTrabajo", typeof(int));
    
            var idTipoHoraParameter = idTipoHora.HasValue ?
                new ObjectParameter("IdTipoHora", idTipoHora) :
                new ObjectParameter("IdTipoHora", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalizacionParameter = fechaFinalizacion.HasValue ?
                new ObjectParameter("FechaFinalizacion", fechaFinalizacion) :
                new ObjectParameter("FechaFinalizacion", typeof(System.DateTime));
    
            var cantidadHorasParameter = cantidadHoras.HasValue ?
                new ObjectParameter("CantidadHoras", cantidadHoras) :
                new ObjectParameter("CantidadHoras", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Pr_Investigador_AgregarHoras", idEquipoDeTrabajoParameter, idTipoHoraParameter, fechaInicioParameter, fechaFinalizacionParameter, cantidadHorasParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_Buscar_Result> Pr_Investigador_Buscar(string nombreInvestigador)
        {
            var nombreInvestigadorParameter = nombreInvestigador != null ?
                new ObjectParameter("NombreInvestigador", nombreInvestigador) :
                new ObjectParameter("NombreInvestigador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_Buscar_Result>("Pr_Investigador_Buscar", nombreInvestigadorParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_BuscarPorCod_Result> Pr_Investigador_BuscarPorCod(string numIdentidad)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_BuscarPorCod_Result>("Pr_Investigador_BuscarPorCod", numIdentidadParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_Consultar_Result> Pr_Investigador_Consultar(string numIdentidad)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_Consultar_Result>("Pr_Investigador_Consultar", numIdentidadParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_ConsultHoras_Result> Pr_Investigador_ConsultHoras(string numIdentidad, string codigoProyecto)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_ConsultHoras_Result>("Pr_Investigador_ConsultHoras", numIdentidadParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_DiscipSelect_Result> Pr_Investigador_DiscipSelect(string estado, Nullable<int> disciplina)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var disciplinaParameter = disciplina.HasValue ?
                new ObjectParameter("Disciplina", disciplina) :
                new ObjectParameter("Disciplina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_DiscipSelect_Result>("Pr_Investigador_DiscipSelect", estadoParameter, disciplinaParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_EscuelaSelect_Result> Pr_Investigador_EscuelaSelect(string estado, Nullable<int> escuela)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var escuelaParameter = escuela.HasValue ?
                new ObjectParameter("Escuela", escuela) :
                new ObjectParameter("Escuela", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_EscuelaSelect_Result>("Pr_Investigador_EscuelaSelect", estadoParameter, escuelaParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_EstadoSelect_Result> Pr_Investigador_EstadoSelect(string estado)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_EstadoSelect_Result>("Pr_Investigador_EstadoSelect", estadoParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_InfPendientes_Result> Pr_Investigador_InfPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_InfPendientes_Result>("Pr_Investigador_InfPendientes");
        }
    
        public virtual ObjectResult<Pr_Investigador_SelectCoord_Result> Pr_Investigador_SelectCoord()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_SelectCoord_Result>("Pr_Investigador_SelectCoord");
        }
    
        public virtual ObjectResult<Pr_Investigador_SelectDiscip_Result> Pr_Investigador_SelectDiscip(string numIdentidad)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_SelectDiscip_Result>("Pr_Investigador_SelectDiscip", numIdentidadParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_SelectEscuela_Result> Pr_Investigador_SelectEscuela(string numIdentidad)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_SelectEscuela_Result>("Pr_Investigador_SelectEscuela", numIdentidadParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_SelectIdiomas_Result> Pr_Investigador_SelectIdiomas(string numIdentidad)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_SelectIdiomas_Result>("Pr_Investigador_SelectIdiomas", numIdentidadParameter);
        }
    
        public virtual ObjectResult<Pr_Investigador_SexoSelect_Result> Pr_Investigador_SexoSelect(string sexo)
        {
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Investigador_SexoSelect_Result>("Pr_Investigador_SexoSelect", sexoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Meta_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Meta_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_Meta_Insertar_Result> Pr_Meta_Insertar(string nombre, Nullable<bool> estaCumplida, Nullable<int> idObjectivoEspecifico, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var estaCumplidaParameter = estaCumplida.HasValue ?
                new ObjectParameter("EstaCumplida", estaCumplida) :
                new ObjectParameter("EstaCumplida", typeof(bool));
    
            var idObjectivoEspecificoParameter = idObjectivoEspecifico.HasValue ?
                new ObjectParameter("IdObjectivoEspecifico", idObjectivoEspecifico) :
                new ObjectParameter("IdObjectivoEspecifico", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Meta_Insertar_Result>("Pr_Meta_Insertar", nombreParameter, estaCumplidaParameter, idObjectivoEspecificoParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<Pr_Meta_Seleccionar_Result> Pr_Meta_Seleccionar(Nullable<int> idObjetivoEspecifico)
        {
            var idObjetivoEspecificoParameter = idObjetivoEspecifico.HasValue ?
                new ObjectParameter("IdObjetivoEspecifico", idObjetivoEspecifico) :
                new ObjectParameter("IdObjetivoEspecifico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Meta_Seleccionar_Result>("Pr_Meta_Seleccionar", idObjetivoEspecificoParameter);
        }
    
        public virtual ObjectResult<Pr_ObjEspecifico_GetByCodigo_Result> Pr_ObjEspecifico_GetByCodigo(Nullable<int> idObjetivoEspecifico)
        {
            var idObjetivoEspecificoParameter = idObjetivoEspecifico.HasValue ?
                new ObjectParameter("IdObjetivoEspecifico", idObjetivoEspecifico) :
                new ObjectParameter("IdObjetivoEspecifico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ObjEspecifico_GetByCodigo_Result>("Pr_ObjEspecifico_GetByCodigo", idObjetivoEspecificoParameter);
        }
    
        public virtual ObjectResult<Pr_ObjetivoEspecifico_Seleccionar_Result> Pr_ObjetivoEspecifico_Seleccionar(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ObjetivoEspecifico_Seleccionar_Result>("Pr_ObjetivoEspecifico_Seleccionar", codigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_PalabraClave_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_PalabraClave_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_PalabraClave_Insertar_Result> Pr_PalabraClave_Insertar(string palabraClave, string codigoProyecto)
        {
            var palabraClaveParameter = palabraClave != null ?
                new ObjectParameter("PalabraClave", palabraClave) :
                new ObjectParameter("PalabraClave", typeof(string));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_PalabraClave_Insertar_Result>("Pr_PalabraClave_Insertar", palabraClaveParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_PalabrasClave_SeleccionarXProyecto_Result> Pr_PalabrasClave_SeleccionarXProyecto(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_PalabrasClave_SeleccionarXProyecto_Result>("Pr_PalabrasClave_SeleccionarXProyecto", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_PlanDeAccion_ObjGenModificar(string codigoProyecto, string nuevoObjGeneral)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            var nuevoObjGeneralParameter = nuevoObjGeneral != null ?
                new ObjectParameter("NuevoObjGeneral", nuevoObjGeneral) :
                new ObjectParameter("NuevoObjGeneral", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_PlanDeAccion_ObjGenModificar", codigoProyectoParameter, nuevoObjGeneralParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_PresupuestoProyecto_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_PresupuestoProyecto_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_PresupuestoProyecto_Insertar_Result> Pr_PresupuestoProyecto_Insertar(Nullable<int> idFuenteFinanciamiento, string organizacion, Nullable<int> idPartida, Nullable<int> ano, Nullable<int> monto, string codigoProyecto)
        {
            var idFuenteFinanciamientoParameter = idFuenteFinanciamiento.HasValue ?
                new ObjectParameter("IdFuenteFinanciamiento", idFuenteFinanciamiento) :
                new ObjectParameter("IdFuenteFinanciamiento", typeof(int));
    
            var organizacionParameter = organizacion != null ?
                new ObjectParameter("Organizacion", organizacion) :
                new ObjectParameter("Organizacion", typeof(string));
    
            var idPartidaParameter = idPartida.HasValue ?
                new ObjectParameter("IdPartida", idPartida) :
                new ObjectParameter("IdPartida", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(int));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(int));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_PresupuestoProyecto_Insertar_Result>("Pr_PresupuestoProyecto_Insertar", idFuenteFinanciamientoParameter, organizacionParameter, idPartidaParameter, anoParameter, montoParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_PresupuestoProyecto_Seleccionar_Result> Pr_PresupuestoProyecto_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_PresupuestoProyecto_Seleccionar_Result>("Pr_PresupuestoProyecto_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_ProductoObjetivo_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_ProductoObjetivo_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_ProductoObjetivo_Insertar_Result> Pr_ProductoObjetivo_Insertar(string actividad, string idInvestigadorEncargado, Nullable<int> idColaboradorEncargado, Nullable<int> idNivelDeResponsabilidad, string nombre, Nullable<int> idObjetivoEspecifico, Nullable<int> ano, Nullable<int> trimestre, Nullable<System.DateTime> fecha)
        {
            var actividadParameter = actividad != null ?
                new ObjectParameter("Actividad", actividad) :
                new ObjectParameter("Actividad", typeof(string));
    
            var idInvestigadorEncargadoParameter = idInvestigadorEncargado != null ?
                new ObjectParameter("IdInvestigadorEncargado", idInvestigadorEncargado) :
                new ObjectParameter("IdInvestigadorEncargado", typeof(string));
    
            var idColaboradorEncargadoParameter = idColaboradorEncargado.HasValue ?
                new ObjectParameter("IdColaboradorEncargado", idColaboradorEncargado) :
                new ObjectParameter("IdColaboradorEncargado", typeof(int));
    
            var idNivelDeResponsabilidadParameter = idNivelDeResponsabilidad.HasValue ?
                new ObjectParameter("IdNivelDeResponsabilidad", idNivelDeResponsabilidad) :
                new ObjectParameter("IdNivelDeResponsabilidad", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var idObjetivoEspecificoParameter = idObjetivoEspecifico.HasValue ?
                new ObjectParameter("IdObjetivoEspecifico", idObjetivoEspecifico) :
                new ObjectParameter("IdObjetivoEspecifico", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(int));
    
            var trimestreParameter = trimestre.HasValue ?
                new ObjectParameter("Trimestre", trimestre) :
                new ObjectParameter("Trimestre", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProductoObjetivo_Insertar_Result>("Pr_ProductoObjetivo_Insertar", actividadParameter, idInvestigadorEncargadoParameter, idColaboradorEncargadoParameter, idNivelDeResponsabilidadParameter, nombreParameter, idObjetivoEspecificoParameter, anoParameter, trimestreParameter, fechaParameter);
        }
    
        public virtual ObjectResult<Pr_ProductoObjetivo_Seleccionar_Result> Pr_ProductoObjetivo_Seleccionar(Nullable<int> idObjetivoEspecifico)
        {
            var idObjetivoEspecificoParameter = idObjetivoEspecifico.HasValue ?
                new ObjectParameter("IdObjetivoEspecifico", idObjetivoEspecifico) :
                new ObjectParameter("IdObjetivoEspecifico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProductoObjetivo_Seleccionar_Result>("Pr_ProductoObjetivo_Seleccionar", idObjetivoEspecificoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Proyecto_AmpliarFecha(Nullable<System.DateTime> fechaAprobacion, Nullable<System.DateTime> nuevaFechaFinalizacion, Nullable<System.DateTime> viejaFechaFinalizacion, string observaciones, string codigo)
        {
            var fechaAprobacionParameter = fechaAprobacion.HasValue ?
                new ObjectParameter("FechaAprobacion", fechaAprobacion) :
                new ObjectParameter("FechaAprobacion", typeof(System.DateTime));
    
            var nuevaFechaFinalizacionParameter = nuevaFechaFinalizacion.HasValue ?
                new ObjectParameter("NuevaFechaFinalizacion", nuevaFechaFinalizacion) :
                new ObjectParameter("NuevaFechaFinalizacion", typeof(System.DateTime));
    
            var viejaFechaFinalizacionParameter = viejaFechaFinalizacion.HasValue ?
                new ObjectParameter("ViejaFechaFinalizacion", viejaFechaFinalizacion) :
                new ObjectParameter("ViejaFechaFinalizacion", typeof(System.DateTime));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Proyecto_AmpliarFecha", fechaAprobacionParameter, nuevaFechaFinalizacionParameter, viejaFechaFinalizacionParameter, observacionesParameter, codigoParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_Buscar_Result> Pr_Proyecto_Buscar(string criterioBusqueda, string parametro)
        {
            var criterioBusquedaParameter = criterioBusqueda != null ?
                new ObjectParameter("CriterioBusqueda", criterioBusqueda) :
                new ObjectParameter("CriterioBusqueda", typeof(string));
    
            var parametroParameter = parametro != null ?
                new ObjectParameter("Parametro", parametro) :
                new ObjectParameter("Parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_Buscar_Result>("Pr_Proyecto_Buscar", criterioBusquedaParameter, parametroParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Proyecto_CambiarInvCoord(string codigo, string numIdentidad)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Proyecto_CambiarInvCoord", codigoParameter, numIdentidadParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_Consultar_Result> Pr_Proyecto_Consultar(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_Consultar_Result>("Pr_Proyecto_Consultar", codigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Proyecto_EliminarInv(string numIdentidad, Nullable<int> idSetDatos)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            var idSetDatosParameter = idSetDatos.HasValue ?
                new ObjectParameter("IdSetDatos", idSetDatos) :
                new ObjectParameter("IdSetDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Proyecto_EliminarInv", numIdentidadParameter, idSetDatosParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_InfPendientes_Result> Pr_Proyecto_InfPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_InfPendientes_Result>("Pr_Proyecto_InfPendientes");
        }
    
        public virtual ObjectResult<Pr_Proyecto_InvParticipante_Result> Pr_Proyecto_InvParticipante(string numIdentidad)
        {
            var numIdentidadParameter = numIdentidad != null ?
                new ObjectParameter("NumIdentidad", numIdentidad) :
                new ObjectParameter("NumIdentidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_InvParticipante_Result>("Pr_Proyecto_InvParticipante", numIdentidadParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Proyecto_Modificar(string codigo, Nullable<System.DateTime> nuevaFechaIngreso, string nuevoNombre, string nuevoObjetivoGeneral, Nullable<int> nuevoIdEstado, Nullable<int> nuevoIdTipoProyecto, Nullable<int> nuevoIdTipoProceso, Nullable<int> nuevoIdModalidad, string nuevaActaVIE, string nuevaActaEscuela, Nullable<System.DateTime> nuevaFechaAprobacion, Nullable<System.DateTime> nuevaFechaInicio, string nuevaDescripcion, string nuevaJustificacion)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nuevaFechaIngresoParameter = nuevaFechaIngreso.HasValue ?
                new ObjectParameter("NuevaFechaIngreso", nuevaFechaIngreso) :
                new ObjectParameter("NuevaFechaIngreso", typeof(System.DateTime));
    
            var nuevoNombreParameter = nuevoNombre != null ?
                new ObjectParameter("NuevoNombre", nuevoNombre) :
                new ObjectParameter("NuevoNombre", typeof(string));
    
            var nuevoObjetivoGeneralParameter = nuevoObjetivoGeneral != null ?
                new ObjectParameter("NuevoObjetivoGeneral", nuevoObjetivoGeneral) :
                new ObjectParameter("NuevoObjetivoGeneral", typeof(string));
    
            var nuevoIdEstadoParameter = nuevoIdEstado.HasValue ?
                new ObjectParameter("NuevoIdEstado", nuevoIdEstado) :
                new ObjectParameter("NuevoIdEstado", typeof(int));
    
            var nuevoIdTipoProyectoParameter = nuevoIdTipoProyecto.HasValue ?
                new ObjectParameter("NuevoIdTipoProyecto", nuevoIdTipoProyecto) :
                new ObjectParameter("NuevoIdTipoProyecto", typeof(int));
    
            var nuevoIdTipoProcesoParameter = nuevoIdTipoProceso.HasValue ?
                new ObjectParameter("NuevoIdTipoProceso", nuevoIdTipoProceso) :
                new ObjectParameter("NuevoIdTipoProceso", typeof(int));
    
            var nuevoIdModalidadParameter = nuevoIdModalidad.HasValue ?
                new ObjectParameter("NuevoIdModalidad", nuevoIdModalidad) :
                new ObjectParameter("NuevoIdModalidad", typeof(int));
    
            var nuevaActaVIEParameter = nuevaActaVIE != null ?
                new ObjectParameter("NuevaActaVIE", nuevaActaVIE) :
                new ObjectParameter("NuevaActaVIE", typeof(string));
    
            var nuevaActaEscuelaParameter = nuevaActaEscuela != null ?
                new ObjectParameter("NuevaActaEscuela", nuevaActaEscuela) :
                new ObjectParameter("NuevaActaEscuela", typeof(string));
    
            var nuevaFechaAprobacionParameter = nuevaFechaAprobacion.HasValue ?
                new ObjectParameter("NuevaFechaAprobacion", nuevaFechaAprobacion) :
                new ObjectParameter("NuevaFechaAprobacion", typeof(System.DateTime));
    
            var nuevaFechaInicioParameter = nuevaFechaInicio.HasValue ?
                new ObjectParameter("NuevaFechaInicio", nuevaFechaInicio) :
                new ObjectParameter("NuevaFechaInicio", typeof(System.DateTime));
    
            var nuevaDescripcionParameter = nuevaDescripcion != null ?
                new ObjectParameter("NuevaDescripcion", nuevaDescripcion) :
                new ObjectParameter("NuevaDescripcion", typeof(string));
    
            var nuevaJustificacionParameter = nuevaJustificacion != null ?
                new ObjectParameter("NuevaJustificacion", nuevaJustificacion) :
                new ObjectParameter("NuevaJustificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Proyecto_Modificar", codigoParameter, nuevaFechaIngresoParameter, nuevoNombreParameter, nuevoObjetivoGeneralParameter, nuevoIdEstadoParameter, nuevoIdTipoProyectoParameter, nuevoIdTipoProcesoParameter, nuevoIdModalidadParameter, nuevaActaVIEParameter, nuevaActaEscuelaParameter, nuevaFechaAprobacionParameter, nuevaFechaInicioParameter, nuevaDescripcionParameter, nuevaJustificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Proyecto_PermisosModificar(string codigo, Nullable<System.DateTime> nuevaFechaIngreso, string nuevoNombre, string nuevoObjetivoGeneral, Nullable<int> nuevoIdEstado, Nullable<int> nuevoIdTipoProyecto, Nullable<int> nuevoIdTipoProceso, Nullable<int> nuevoIdModalidad, string nuevaActaVIE, string nuevaActaEscuela, Nullable<System.DateTime> nuevaFechaAprobacion, Nullable<System.DateTime> nuevaFechaInicio, string nuevaDescripcion, string nuevaJustificacion)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nuevaFechaIngresoParameter = nuevaFechaIngreso.HasValue ?
                new ObjectParameter("NuevaFechaIngreso", nuevaFechaIngreso) :
                new ObjectParameter("NuevaFechaIngreso", typeof(System.DateTime));
    
            var nuevoNombreParameter = nuevoNombre != null ?
                new ObjectParameter("NuevoNombre", nuevoNombre) :
                new ObjectParameter("NuevoNombre", typeof(string));
    
            var nuevoObjetivoGeneralParameter = nuevoObjetivoGeneral != null ?
                new ObjectParameter("NuevoObjetivoGeneral", nuevoObjetivoGeneral) :
                new ObjectParameter("NuevoObjetivoGeneral", typeof(string));
    
            var nuevoIdEstadoParameter = nuevoIdEstado.HasValue ?
                new ObjectParameter("NuevoIdEstado", nuevoIdEstado) :
                new ObjectParameter("NuevoIdEstado", typeof(int));
    
            var nuevoIdTipoProyectoParameter = nuevoIdTipoProyecto.HasValue ?
                new ObjectParameter("NuevoIdTipoProyecto", nuevoIdTipoProyecto) :
                new ObjectParameter("NuevoIdTipoProyecto", typeof(int));
    
            var nuevoIdTipoProcesoParameter = nuevoIdTipoProceso.HasValue ?
                new ObjectParameter("NuevoIdTipoProceso", nuevoIdTipoProceso) :
                new ObjectParameter("NuevoIdTipoProceso", typeof(int));
    
            var nuevoIdModalidadParameter = nuevoIdModalidad.HasValue ?
                new ObjectParameter("NuevoIdModalidad", nuevoIdModalidad) :
                new ObjectParameter("NuevoIdModalidad", typeof(int));
    
            var nuevaActaVIEParameter = nuevaActaVIE != null ?
                new ObjectParameter("NuevaActaVIE", nuevaActaVIE) :
                new ObjectParameter("NuevaActaVIE", typeof(string));
    
            var nuevaActaEscuelaParameter = nuevaActaEscuela != null ?
                new ObjectParameter("NuevaActaEscuela", nuevaActaEscuela) :
                new ObjectParameter("NuevaActaEscuela", typeof(string));
    
            var nuevaFechaAprobacionParameter = nuevaFechaAprobacion.HasValue ?
                new ObjectParameter("NuevaFechaAprobacion", nuevaFechaAprobacion) :
                new ObjectParameter("NuevaFechaAprobacion", typeof(System.DateTime));
    
            var nuevaFechaInicioParameter = nuevaFechaInicio.HasValue ?
                new ObjectParameter("NuevaFechaInicio", nuevaFechaInicio) :
                new ObjectParameter("NuevaFechaInicio", typeof(System.DateTime));
    
            var nuevaDescripcionParameter = nuevaDescripcion != null ?
                new ObjectParameter("NuevaDescripcion", nuevaDescripcion) :
                new ObjectParameter("NuevaDescripcion", typeof(string));
    
            var nuevaJustificacionParameter = nuevaJustificacion != null ?
                new ObjectParameter("NuevaJustificacion", nuevaJustificacion) :
                new ObjectParameter("NuevaJustificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Proyecto_PermisosModificar", codigoParameter, nuevaFechaIngresoParameter, nuevoNombreParameter, nuevoObjetivoGeneralParameter, nuevoIdEstadoParameter, nuevoIdTipoProyectoParameter, nuevoIdTipoProcesoParameter, nuevoIdModalidadParameter, nuevaActaVIEParameter, nuevaActaEscuelaParameter, nuevaFechaAprobacionParameter, nuevaFechaInicioParameter, nuevaDescripcionParameter, nuevaJustificacionParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReporteBeneficiaria_Result> Pr_Proyecto_ReporteBeneficiaria(string estadoBusqueda, Nullable<int> idBeneficiaria)
        {
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            var idBeneficiariaParameter = idBeneficiaria.HasValue ?
                new ObjectParameter("IdBeneficiaria", idBeneficiaria) :
                new ObjectParameter("IdBeneficiaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReporteBeneficiaria_Result>("Pr_Proyecto_ReporteBeneficiaria", estadoBusquedaParameter, idBeneficiariaParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReporteEscuelas_Result> Pr_Proyecto_ReporteEscuelas(Nullable<System.DateTime> fechaRangoInicio, Nullable<System.DateTime> fechaRangoFinal, Nullable<int> idDepartamento, Nullable<int> idTipoDepartamento, string estadoBusqueda)
        {
            var fechaRangoInicioParameter = fechaRangoInicio.HasValue ?
                new ObjectParameter("FechaRangoInicio", fechaRangoInicio) :
                new ObjectParameter("FechaRangoInicio", typeof(System.DateTime));
    
            var fechaRangoFinalParameter = fechaRangoFinal.HasValue ?
                new ObjectParameter("FechaRangoFinal", fechaRangoFinal) :
                new ObjectParameter("FechaRangoFinal", typeof(System.DateTime));
    
            var idDepartamentoParameter = idDepartamento.HasValue ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(int));
    
            var idTipoDepartamentoParameter = idTipoDepartamento.HasValue ?
                new ObjectParameter("IdTipoDepartamento", idTipoDepartamento) :
                new ObjectParameter("IdTipoDepartamento", typeof(int));
    
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReporteEscuelas_Result>("Pr_Proyecto_ReporteEscuelas", fechaRangoInicioParameter, fechaRangoFinalParameter, idDepartamentoParameter, idTipoDepartamentoParameter, estadoBusquedaParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReporteEstado_Result> Pr_Proyecto_ReporteEstado(string estadoBusqueda)
        {
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReporteEstado_Result>("Pr_Proyecto_ReporteEstado", estadoBusquedaParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReporteHoras_Result> Pr_Proyecto_ReporteHoras(Nullable<System.DateTime> fechaRangoInicio, Nullable<System.DateTime> fechaRangoFinal, Nullable<int> idDepartamento, Nullable<int> idTipoDepartamento, string estadoBusqueda)
        {
            var fechaRangoInicioParameter = fechaRangoInicio.HasValue ?
                new ObjectParameter("FechaRangoInicio", fechaRangoInicio) :
                new ObjectParameter("FechaRangoInicio", typeof(System.DateTime));
    
            var fechaRangoFinalParameter = fechaRangoFinal.HasValue ?
                new ObjectParameter("FechaRangoFinal", fechaRangoFinal) :
                new ObjectParameter("FechaRangoFinal", typeof(System.DateTime));
    
            var idDepartamentoParameter = idDepartamento.HasValue ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(int));
    
            var idTipoDepartamentoParameter = idTipoDepartamento.HasValue ?
                new ObjectParameter("IdTipoDepartamento", idTipoDepartamento) :
                new ObjectParameter("IdTipoDepartamento", typeof(int));
    
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReporteHoras_Result>("Pr_Proyecto_ReporteHoras", fechaRangoInicioParameter, fechaRangoFinalParameter, idDepartamentoParameter, idTipoDepartamentoParameter, estadoBusquedaParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReporteModalidad_Result> Pr_Proyecto_ReporteModalidad(string estadoBusqueda, Nullable<int> idModalidadProyecto)
        {
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            var idModalidadProyectoParameter = idModalidadProyecto.HasValue ?
                new ObjectParameter("IdModalidadProyecto", idModalidadProyecto) :
                new ObjectParameter("IdModalidadProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReporteModalidad_Result>("Pr_Proyecto_ReporteModalidad", estadoBusquedaParameter, idModalidadProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReportePresup_Result> Pr_Proyecto_ReportePresup(Nullable<System.DateTime> fechaRangoInicio, Nullable<System.DateTime> fechaRangoFinal, Nullable<int> idDepartamento, Nullable<int> idTipoDepartamento, string estadoBusqueda)
        {
            var fechaRangoInicioParameter = fechaRangoInicio.HasValue ?
                new ObjectParameter("FechaRangoInicio", fechaRangoInicio) :
                new ObjectParameter("FechaRangoInicio", typeof(System.DateTime));
    
            var fechaRangoFinalParameter = fechaRangoFinal.HasValue ?
                new ObjectParameter("FechaRangoFinal", fechaRangoFinal) :
                new ObjectParameter("FechaRangoFinal", typeof(System.DateTime));
    
            var idDepartamentoParameter = idDepartamento.HasValue ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(int));
    
            var idTipoDepartamentoParameter = idTipoDepartamento.HasValue ?
                new ObjectParameter("IdTipoDepartamento", idTipoDepartamento) :
                new ObjectParameter("IdTipoDepartamento", typeof(int));
    
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReportePresup_Result>("Pr_Proyecto_ReportePresup", fechaRangoInicioParameter, fechaRangoFinalParameter, idDepartamentoParameter, idTipoDepartamentoParameter, estadoBusquedaParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReporteTipoProy_Result> Pr_Proyecto_ReporteTipoProy(string estadoBusqueda, Nullable<int> idTipoProyecto)
        {
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            var idTipoProyectoParameter = idTipoProyecto.HasValue ?
                new ObjectParameter("IdTipoProyecto", idTipoProyecto) :
                new ObjectParameter("IdTipoProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReporteTipoProy_Result>("Pr_Proyecto_ReporteTipoProy", estadoBusquedaParameter, idTipoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_ReporteUbicacion_Result> Pr_Proyecto_ReporteUbicacion(string estadoBusqueda, Nullable<int> idPais, Nullable<int> idRegion, Nullable<int> idProvinvia)
        {
            var estadoBusquedaParameter = estadoBusqueda != null ?
                new ObjectParameter("EstadoBusqueda", estadoBusqueda) :
                new ObjectParameter("EstadoBusqueda", typeof(string));
    
            var idPaisParameter = idPais.HasValue ?
                new ObjectParameter("IdPais", idPais) :
                new ObjectParameter("IdPais", typeof(int));
    
            var idRegionParameter = idRegion.HasValue ?
                new ObjectParameter("IdRegion", idRegion) :
                new ObjectParameter("IdRegion", typeof(int));
    
            var idProvinviaParameter = idProvinvia.HasValue ?
                new ObjectParameter("IdProvinvia", idProvinvia) :
                new ObjectParameter("IdProvinvia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_ReporteUbicacion_Result>("Pr_Proyecto_ReporteUbicacion", estadoBusquedaParameter, idPaisParameter, idRegionParameter, idProvinviaParameter);
        }
    
        public virtual ObjectResult<Pr_Proyecto_Seleccionar_Result> Pr_Proyecto_Seleccionar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_Seleccionar_Result>("Pr_Proyecto_Seleccionar");
        }
    
        public virtual ObjectResult<Pr_Proyecto_SelectActividades_Result> Pr_Proyecto_SelectActividades(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Proyecto_SelectActividades_Result>("Pr_Proyecto_SelectActividades", codigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_ProyectoXBeneficiaria_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_ProyectoXBeneficiaria_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXBeneficiaria_Insertar_Result> Pr_ProyectoXBeneficiaria_Insertar(string codigoProyecto, Nullable<int> idPoblacionBeneficiaria)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            var idPoblacionBeneficiariaParameter = idPoblacionBeneficiaria.HasValue ?
                new ObjectParameter("IdPoblacionBeneficiaria", idPoblacionBeneficiaria) :
                new ObjectParameter("IdPoblacionBeneficiaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXBeneficiaria_Insertar_Result>("Pr_ProyectoXBeneficiaria_Insertar", codigoProyectoParameter, idPoblacionBeneficiariaParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXBeneficiaria_Seleccionar_Result> Pr_ProyectoXBeneficiaria_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXBeneficiaria_Seleccionar_Result>("Pr_ProyectoXBeneficiaria_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_ProyectoXDepartamento_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_ProyectoXDepartamento_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXDepartamento_Insertar_Result> Pr_ProyectoXDepartamento_Insertar(string codigoProyecto, Nullable<int> idDepartamento, Nullable<int> idTipoDepartamento)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            var idDepartamentoParameter = idDepartamento.HasValue ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(int));
    
            var idTipoDepartamentoParameter = idTipoDepartamento.HasValue ?
                new ObjectParameter("IdTipoDepartamento", idTipoDepartamento) :
                new ObjectParameter("IdTipoDepartamento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXDepartamento_Insertar_Result>("Pr_ProyectoXDepartamento_Insertar", codigoProyectoParameter, idDepartamentoParameter, idTipoDepartamentoParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXDepartamentos_Seleccionar_Result> Pr_ProyectoXDepartamentos_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXDepartamentos_Seleccionar_Result>("Pr_ProyectoXDepartamentos_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_ProyectoXFrascati_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_ProyectoXFrascati_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXFrascati_Insertar_Result> Pr_ProyectoXFrascati_Insertar(string codigoProyecto, Nullable<int> idSubArea, Nullable<int> idArea)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            var idSubAreaParameter = idSubArea.HasValue ?
                new ObjectParameter("IdSubArea", idSubArea) :
                new ObjectParameter("IdSubArea", typeof(int));
    
            var idAreaParameter = idArea.HasValue ?
                new ObjectParameter("IdArea", idArea) :
                new ObjectParameter("IdArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXFrascati_Insertar_Result>("Pr_ProyectoXFrascati_Insertar", codigoProyectoParameter, idSubAreaParameter, idAreaParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXFrascati_Seleccionar_Result> Pr_ProyectoXFrascati_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXFrascati_Seleccionar_Result>("Pr_ProyectoXFrascati_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_ProyectoXODS_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_ProyectoXODS_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXODS_Insertar_Result> Pr_ProyectoXODS_Insertar(string codigoProyecto, Nullable<int> idSubODS, Nullable<int> idODS)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            var idSubODSParameter = idSubODS.HasValue ?
                new ObjectParameter("IdSubODS", idSubODS) :
                new ObjectParameter("IdSubODS", typeof(int));
    
            var idODSParameter = idODS.HasValue ?
                new ObjectParameter("IdODS", idODS) :
                new ObjectParameter("IdODS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXODS_Insertar_Result>("Pr_ProyectoXODS_Insertar", codigoProyectoParameter, idSubODSParameter, idODSParameter);
        }
    
        public virtual ObjectResult<Pr_ProyectoXODS_Seleccionar_Result> Pr_ProyectoXODS_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProyectoXODS_Seleccionar_Result>("Pr_ProyectoXODS_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_Riesgo_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_Riesgo_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_Riesgo_Insertar_Result> Pr_Riesgo_Insertar(string nombre, string accionesMitagacion, Nullable<int> idObjetivoEspecifico)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var accionesMitagacionParameter = accionesMitagacion != null ?
                new ObjectParameter("AccionesMitagacion", accionesMitagacion) :
                new ObjectParameter("AccionesMitagacion", typeof(string));
    
            var idObjetivoEspecificoParameter = idObjetivoEspecifico.HasValue ?
                new ObjectParameter("IdObjetivoEspecifico", idObjetivoEspecifico) :
                new ObjectParameter("IdObjetivoEspecifico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Riesgo_Insertar_Result>("Pr_Riesgo_Insertar", nombreParameter, accionesMitagacionParameter, idObjetivoEspecificoParameter);
        }
    
        public virtual ObjectResult<Pr_Riesgo_Seleccionar_Result> Pr_Riesgo_Seleccionar(Nullable<int> idObjetivoEspecifico)
        {
            var idObjetivoEspecificoParameter = idObjetivoEspecifico.HasValue ?
                new ObjectParameter("IdObjetivoEspecifico", idObjetivoEspecifico) :
                new ObjectParameter("IdObjetivoEspecifico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Riesgo_Seleccionar_Result>("Pr_Riesgo_Seleccionar", idObjetivoEspecificoParameter);
        }
    
        public virtual ObjectResult<Pr_SubAreaFrascati_Consultar_Result> Pr_SubAreaFrascati_Consultar(Nullable<int> idAreaFrascati)
        {
            var idAreaFrascatiParameter = idAreaFrascati.HasValue ?
                new ObjectParameter("IdAreaFrascati", idAreaFrascati) :
                new ObjectParameter("IdAreaFrascati", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_SubAreaFrascati_Consultar_Result>("Pr_SubAreaFrascati_Consultar", idAreaFrascatiParameter);
        }
    
        public virtual ObjectResult<Pr_SubODS_Consultar_Result> Pr_SubODS_Consultar(Nullable<int> idODS)
        {
            var idODSParameter = idODS.HasValue ?
                new ObjectParameter("IdODS", idODS) :
                new ObjectParameter("IdODS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_SubODS_Consultar_Result>("Pr_SubODS_Consultar", idODSParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pr_UbicacionGeografica_Eliminar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pr_UbicacionGeografica_Eliminar", idParameter);
        }
    
        public virtual ObjectResult<Pr_UbicacionGeografica_Insertar_Result> Pr_UbicacionGeografica_Insertar(Nullable<int> idPais, Nullable<int> idRegion, Nullable<int> idProvincia, string codigoProyecto)
        {
            var idPaisParameter = idPais.HasValue ?
                new ObjectParameter("IdPais", idPais) :
                new ObjectParameter("IdPais", typeof(int));
    
            var idRegionParameter = idRegion.HasValue ?
                new ObjectParameter("IdRegion", idRegion) :
                new ObjectParameter("IdRegion", typeof(int));
    
            var idProvinciaParameter = idProvincia.HasValue ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(int));
    
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_UbicacionGeografica_Insertar_Result>("Pr_UbicacionGeografica_Insertar", idPaisParameter, idRegionParameter, idProvinciaParameter, codigoProyectoParameter);
        }
    
        public virtual ObjectResult<Pr_UbicacionGeografica_Seleccionar_Result> Pr_UbicacionGeografica_Seleccionar(string codigoProyecto)
        {
            var codigoProyectoParameter = codigoProyecto != null ?
                new ObjectParameter("CodigoProyecto", codigoProyecto) :
                new ObjectParameter("CodigoProyecto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_UbicacionGeografica_Seleccionar_Result>("Pr_UbicacionGeografica_Seleccionar", codigoProyectoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
