//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class NivelIdioma
    {
        public NivelIdioma()
        {
            this.InvestigadorXIdioma = new HashSet<InvestigadorXIdioma>();
            this.InvestigadorXIdioma1 = new HashSet<InvestigadorXIdioma>();
            this.InvestigadorXIdioma2 = new HashSet<InvestigadorXIdioma>();
        }
    
        public int Id { get; set; }
        public string NivelIdioma1 { get; set; }
    
        public virtual ICollection<InvestigadorXIdioma> InvestigadorXIdioma { get; set; }
        public virtual ICollection<InvestigadorXIdioma> InvestigadorXIdioma1 { get; set; }
        public virtual ICollection<InvestigadorXIdioma> InvestigadorXIdioma2 { get; set; }
    }
}
