//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivoEspecifico
    {
        public ObjetivoEspecifico()
        {
            this.Meta = new HashSet<Meta>();
            this.ProductoObjetivo = new HashSet<ProductoObjetivo>();
            this.Riesgo = new HashSet<Riesgo>();
        }
    
        public int Id { get; set; }
        public string ObjetivoEspecifico1 { get; set; }
        public int IdPlanDeAccion { get; set; }
        public string Metodologia { get; set; }
    
        public virtual ICollection<Meta> Meta { get; set; }
        public virtual PlanDeAccion PlanDeAccion { get; set; }
        public virtual ICollection<ProductoObjetivo> ProductoObjetivo { get; set; }
        public virtual ICollection<Riesgo> Riesgo { get; set; }
    }
}
