//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Investigador = new HashSet<Investigador>();
            this.UbicacionGeografica = new HashSet<UbicacionGeografica>();
        }
    
        public int Id { get; set; }
        public string NombrePais { get; set; }
    
        public virtual ICollection<Investigador> Investigador { get; set; }
        public virtual ICollection<UbicacionGeografica> UbicacionGeografica { get; set; }
    }
}
