//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanDeAccion
    {
        public PlanDeAccion()
        {
            this.ObjetivoEspecifico = new HashSet<ObjetivoEspecifico>();
            this.PlanteamientoProyecto = new HashSet<PlanteamientoProyecto>();
        }
    
        public int Id { get; set; }
        public string ObjetivoGeneral { get; set; }
    
        public virtual ICollection<ObjetivoEspecifico> ObjetivoEspecifico { get; set; }
        public virtual ICollection<PlanteamientoProyecto> PlanteamientoProyecto { get; set; }
    }
}
