//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanteamientoProyecto
    {
        public PlanteamientoProyecto()
        {
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public int Id { get; set; }
        public string Justificacion { get; set; }
        public string EstadoSituacion { get; set; }
        public int IdPlanDeAccion { get; set; }
        public string EstrategiaAprobacion { get; set; }
    
        public virtual PlanDeAccion PlanDeAccion { get; set; }
        public virtual ICollection<Proyecto> Proyecto { get; set; }
    }
}
