//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoblacionBeneficiaria
    {
        public PoblacionBeneficiaria()
        {
            this.ProyectoXBeneficiaria = new HashSet<ProyectoXBeneficiaria>();
        }
    
        public int Id { get; set; }
        public string NombrePoblacion { get; set; }
    
        public virtual ICollection<ProyectoXBeneficiaria> ProyectoXBeneficiaria { get; set; }
    }
}
