//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestoProyecto
    {
        public int Id { get; set; }
        public int IdFuenteFinanciamiento { get; set; }
        public string Organizacion { get; set; }
        public Nullable<int> IdPartida { get; set; }
        public int Ano { get; set; }
        public int Monto { get; set; }
        public string CodigoProyecto { get; set; }
    
        public virtual FuenteFinanciamiento FuenteFinanciamiento { get; set; }
        public virtual Partida Partida { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
