//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoObjetivo
    {
        public int Id { get; set; }
        public string Actividad { get; set; }
        public string IdInvestigadorEncargado { get; set; }
        public Nullable<int> IdColaboradorEncargado { get; set; }
        public int IdNivelDeResponsabilidad { get; set; }
        public string Nombre { get; set; }
        public int IdObjetivoEspecifico { get; set; }
        public int Ano { get; set; }
        public int Trimestre { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Investigador Investigador { get; set; }
        public virtual NivelDeResponsabilidad NivelDeResponsabilidad { get; set; }
        public virtual ObjetivoEspecifico ObjetivoEspecifico { get; set; }
        public virtual ProductoObjetivo ProductoObjetivo1 { get; set; }
        public virtual ProductoObjetivo ProductoObjetivo2 { get; set; }
    }
}
