//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoXBeneficiaria
    {
        public int Id { get; set; }
        public string CodigoProyecto { get; set; }
        public int IdPoblacionBeneficiaria { get; set; }
    
        public virtual PoblacionBeneficiaria PoblacionBeneficiaria { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
