//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubODS
    {
        public SubODS()
        {
            this.ProyectoXODS = new HashSet<ProyectoXODS>();
        }
    
        public int Id { get; set; }
        public int IdODS { get; set; }
        public string SubODS1 { get; set; }
    
        public virtual ODS ODS { get; set; }
        public virtual ICollection<ProyectoXODS> ProyectoXODS { get; set; }
    }
}
