//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProyecto
    {
        public TipoProyecto()
        {
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public int Id { get; set; }
        public string TipoProyecto1 { get; set; }
    
        public virtual ICollection<Proyecto> Proyecto { get; set; }
    }
}
