//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeIdentificacion
    {
        public TipoDeIdentificacion()
        {
            this.Investigador = new HashSet<Investigador>();
        }
    
        public int Id { get; set; }
        public string TipoIdentificacion { get; set; }
    
        public virtual ICollection<Investigador> Investigador { get; set; }
    }
}
